### ISSUE TITLE
Fatal error when building OpenSceneGraph

### ISSUE THREAD

**Issue by ptz3233** [fgsfdsfgs/openmw-switch-deps#1]
Hi - possibly something is up when Cmake does its config - I am getting this error when installing your version of openSceneGraph -
`[  7%] Building CXX object src/osg/CMakeFiles/osg.dir/GLExtensions.cpp.obj
/openmw-switch-deps-master/OpenSceneGraph/src/osg/GLExtensions.cpp:56:14: fatal error: dlfcn.h: No such file or directory
     #include <dlfcn.h>
              ^~~~~~~~~
compilation terminated.
src/osg/CMakeFiles/osg.dir/build.make:1430: recipe for target 'src/osg/CMakeFiles/osg.dir/GLExtensions.cpp.obj' failed
make[2]: *** [src/osg/CMakeFiles/osg.dir/GLExtensions.cpp.obj] Error 1
CMakeFiles/Makefile2:300: recipe for target 'src/osg/CMakeFiles/osg.dir/all' failed
make[1]: *** [src/osg/CMakeFiles/osg.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

The output of cmake also complains of missing modules but not sure if that is the root issue here.

**Comment by fgsfdsfgs** [comment]
Are you sure you have done exactly as specified in the build instructions?
Have you executed `source $DEVKITPRO/switchvars.sh` before you did anything?

**Comment by fgsfdsfgs** [comment]
Ah, nevermind. I wasn't getting this error because I have a fake dlfcn.h in place. fgsfdsfgs/OpenSceneGraph@c5d59b9d6 should fix this.
As for the missing modules, you might be missing some dependencies. Which modules are you missing?

**Comment by ptz3233** [comment]
Thanks - looks like c5d59b9 gets that file to compile.

`/src/osgDB/DynamicLibrary.cpp` also uses dlfcn.h - I put in some workarounds to get that to compile also.

Making it all the way to ` Building CXX object src/osgViewer/CMakeFiles/osgViewer.dir/GraphicsWindowX11.cpp.obj` now

but get
`In file included from /openmw-switch-deps-master/OpenSceneGraph/include/osgViewer/api/X11/GraphicsWindowX11:23,
                 from /openmw-switch-deps-master/OpenSceneGraph/src/osgViewer/GraphicsWindowX11.cpp:22:
/openmw-switch-deps-master/OpenSceneGraph/include/osgViewer/api/X11/GraphicsHandleX11:28:14: fatal error: X11/X.h: No such file or directory
     #include <X11/X.h>
              ^~~~~~~~~
compilation terminated.`

Was able to fix this by adding `-DOSG_WINDOWING_SYSTEM="None"` in the cmake arguments.
Not sure why I had to do this as line 53 in CmakeLists.txt looks like its supposed to take care of this but I'm not super familiar with cmake.

For the record this is everything cmake complains about:

`-- Could NOT find OpenGL (missing:  OPENGL_gl_LIBRARY)
-- Could NOT find Jasper (missing:  JASPER_LIBRARIES JASPER_INCLUDE_DIR)
-- Could NOT find GDAL (missing:  GDAL_LIBRARY GDAL_INCLUDE_DIR)
-- Checking for module 'gta'
--   No package 'gta' found
-- Trying to find DCMTK expecting DCMTKConfig.cmake
-- Trying to find DCMTK expecting DCMTKConfig.cmake - failed
-- Trying to find DCMTK relying on FindDCMTK.cmake
-- Please set DCMTK_DIR and re-run configure (missing:  DCMTK_config_INCLUDE_DIR DCMTK_dcmdata_INCLUDE_DIR DCMTK_dcmimage_INCLUDE_DIR DCMTK_dcmimgle_INCLUDE_DIR DCMTK_dcmjpeg_INCLUDE_DIR DCMTK_dcmjpls_INCLUDE_DIR DCMTK_dcmnet_INCLUDE_DIR DCMTK_dcmpstat_INCLUDE_DIR DCMTK_dcmqrdb_INCLUDE_DIR DCMTK_dcmsign_INCLUDE_DIR DCMTK_dcmsr_INCLUDE_DIR DCMTK_dcmtls_INCLUDE_DIR DCMTK_ofstd_INCLUDE_DIR DCMTK_oflog_INCLUDE_DIR DCMTK_LIBRARIES)
-- Trying to find DCMTK relying on FindDCMTK.cmake - ok
-- Could NOT find GStreamer (missing:  GSTREAMER_INCLUDE_DIRS GSTREAMER_LIBRARIES GSTREAMER_VERSION GSTREAMER_BASE_INCLUDE_DIRS GSTREAMER_BASE_LIBRARIES GSTREAMER_APP_INCLUDE_DIRS GSTREAMER_APP_LIBRARIES GSTREAMER_PBUTILS_INCLUDE_DIRS GSTREAMER_PBUTILS_LIBRARIES)
-- Could NOT find SDL (missing:  SDL_LIBRARY SDL_INCLUDE_DIR)
-- Checking for module 'cairo'
--   No package 'cairo' found
-- Checking for module 'poppler-glib'
--   No package 'poppler-glib' found
-- Checking for module 'librsvg-2.0>=2.35'
-- Checking for module 'cairo'
--   No package 'cairo' found
-- Checking for module 'gtk+-2.0'
--   No package 'gtk+-2.0' found
-- Checking for module 'gtkglext-x11-1.0'
--   No package 'gtkglext-x11-1.0' found
-- Could NOT find TIFF (missing:  TIFF_LIBRARY TIFF_INCLUDE_DIR)
-- g++ version 8.3.0
-- Checking for module 'xrandr'
--   No package 'xrandr' found
-- Checking for module 'xinerama'
--   No package 'xinerama' found
-- Configuring done
-- Generating done`

Anyways, closing this issue because I was able to compile OSG succesfully.

**Comment by fgsfdsfgs** [comment]
Thanks, I'll fix the other lib. Those modules are all optional and don't exist on the Switch, so it's fine.

**Comment by ptz3233** [comment]
FYI - MyGUI also suffers from the dlfcn issue - 
maybe you can add this to your patch at around line 35 in `MyGUI_DynLib.h`

`\#elif __SWITCH__
 \#    define MYGUI_DYNLIB_HANDLE void*
 \#    define MYGUI_DYNLIB_LOAD( a )  true
 \#    define MYGUI_DYNLIB_GETSYM( a, b )  true
 \#    define MYGUI_DYNLIB_UNLOAD( a ) true
 \#endif``

And change line 23 to this:
`#elif MYGUI_PLATFORM == MYGUI_PLATFORM_LINUX && !defined(__SWITCH__)`
